<?php
$ma_pages = 'podcasts';
require("header.php");
?>


<div class="col-lg-12 ombre pt-5 ">
    <div class="container">


            <div class="row">
                  <img src="assets\img\banniere\podcasts.png" alt="banniere artistes et intervenants"
                        class="img-fluid pb-3">
            </div>

<div class="row">
<div class="col-sm-12">
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/774191071&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/803704240&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-24" title="OVAIRES BOOKÉES #22 // Slam onirique, les Immédianes, culture du viol, humour politique" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKÉES #22 // Slam onirique, les Immédianes, culture du viol, humour politique</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/803699836&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-23" title="OVAIRES BOOKÉES #21 // Queen Blood, Conférence gesticulée, Miyazaki féministe?" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKÉES #21 // Queen Blood, Conférence gesticulée, Miyazaki féministe?</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/803694901&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-22" title="OVAIRES BOOKÉES #20 // Twittosphère, Stop féminicides, films et séries LGBTQIF, humour politique" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKÉES #20 // Twittosphère, Stop féminicides, films et séries LGBTQIF, humour politique</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/803694613&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-21" title="OVAIRES BOOKÉES # 19 // Terre lesbienne, Buffy féministe?, Body Positive" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKÉES # 19 // Terre lesbienne, Buffy féministe?, Body Positive</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/803694172&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-20" title="OVAIRES BOOKÉES #18 // collage #stopféminicides, militantisme lesbien, planète sur Uranus, les Slits" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKÉES #18 // collage #stopféminicides, militantisme lesbien, planète sur Uranus, les Slits</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/803693758&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-19" title="OVAIRES BOOKÉES #17 // Films et séries LGBTQIF" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKÉES #17 // Films et séries LGBTQIF</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/797696104&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-18" title="OVAIRES BOOKEES #16 // Fraca label, Body Positive, vêtements genrés" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKEES #16 // Fraca label, Body Positive, vêtements genrés</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/797666635&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-17" title="OVAIRES BOOKEES #15 // 1ère marche des fiertés d'Amiens" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKEES #15 // 1ère marche des fiertés d'Amiens</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/797645779&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-16" title="OVAIRES BOOKEES #13 // TDOV, lesbienne au Moyen-Âge, contraception, C. Guillaumin, humour féministe" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKEES #13 // TDOV, lesbienne au Moyen-Âge, contraception, C. Guillaumin, humour féministe</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/797614000&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-15" title="OVAIRES BOOKEES #11 // Écoféminisme et convergence des militantismes" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKEES #11 // Écoféminisme et convergence des militantismes</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/797594341&color=%23ffad3f&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/lesbavardes" title="LES BAVARDES" target="_blank" style="color: #cccccc; text-decoration: none;">LES BAVARDES</a> · <a href="https://soundcloud.com/lesbavardes/ovaires-bookees-14" title="OVAIRES BOOKÉES #10 // Red&White, sorcières et dumpster diving" target="_blank" style="color: #cccccc; text-decoration: none;">OVAIRES BOOKÉES #10 // Red&White, sorcières et dumpster diving</a></div>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/557935875&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/553560159&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/553542291&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/553539093&color=%23868586&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/553539093&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="166" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/553523859&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/636911088&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/635837934&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/635781318&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>
<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/635684736&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe>

</div>
</div>


    </div>
</div>

<?php
require("footer.php")
?>